#!/usr/bin/env python2.7

from audio_vars import *

# IPA Pulmonic consonant constructors
places              = ['labial', 'coronal', 'dorsal', 'laryngeal']
sublabial_places    = ['bilabial', 'labio-dental', 'linguo-labial']
subcoronal_places   = ['linguo-labial', 'dental', 'alveolar', 'palato-alveolar', 'retroflex', 'alveolo-palatal']
subdorsal_places    = ['alveolo-palatal', 'palatal', 'velar', 'uvular']
sublaryngeal_places = ['uvular','pharyngeal', 'epiglottal', 'glottal']

manners             = ['nasal', 'stop', 'sibilant-affricate', 'non-sibilant-affricate', 'sibilant-fricative',
                       'non-sibilant-fricative', 'approximant', 'flap', 'trill', 'lateral-affricate',
                       'lateral-fricative', 'lateral-approximant', 'lateral-flap']
# IPA Non-pulmonic consonants
simple_clicks       = []
other_clicks        = []
implosives          = []
ejectives           = []

# IPA Co-articulated consonants
continuants         = []
occlusives          = []

pulmonic_consonants = {
    ('labial'   ,'bilabial'     ,'nasal'                     ):{'ipa_val':u'\u006D\u0325', 'path':audio_path + 'l_b__n'   + audio_ext},
    ('labial'   ,'labio-dental' ,'nasal'                     ):{'ipa_val':u'\u0271\u030A', 'path':audio_path + 'l_ld_n'   + audio_ext},
    ('labial'   ,'linguo-labial','nasal'                     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_n'   + audio_ext},
    ('labial'   ,'bilabial'     ,'stop'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__s'   + audio_ext},
    ('labial'   ,'labio-dental' ,'stop'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_s'   + audio_ext},
    ('labial'   ,'linguo-labial','stop'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_s'   + audio_ext},
    ('labial'   ,'bilabial'     ,'sibilant-affricative'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__sa'  + audio_ext},
    ('labial'   ,'labio-dental' ,'sibilant-affricative'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_sa'  + audio_ext},
    ('labial'   ,'linguo-labial','sibilant-affricative'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_sa'  + audio_ext},
    ('labial'   ,'bilabial'     ,'non-sibilant-affricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__nsa' + audio_ext},
    ('labial'   ,'labio-dental' ,'non-sibilant-affricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_nsa' + audio_ext},
    ('labial'   ,'linguo-labial','non-sibilant-affricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_nsa' + audio_ext},
    ('labial'   ,'bilabial'     ,'approximant'               ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__a'   + audio_ext},
    ('labial'   ,'labio-dental' ,'approximant'               ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_a'   + audio_ext},
    ('labial'   ,'linguo-labial','approximant'               ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_a'   + audio_ext},
    ('labial'   ,'bilabial'     ,'flap'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__f'   + audio_ext},
    ('labial'   ,'labio-dental' ,'flap'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_f'   + audio_ext},
    ('labial'   ,'linguo-labial','flap'                      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_f'   + audio_ext},
    ('labial'   ,'bilabial'     ,'trill'                     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__t'   + audio_ext},
    ('labial'   ,'labio-dental' ,'trill'                     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_t'   + audio_ext},
    ('labial'   ,'linguo-labial','trill'                     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_t'   + audio_ext},
    ('labial'   ,'bilabial'     ,'lateral-affricate'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__laf' + audio_ext},
    ('labial'   ,'labio-dental' ,'lateral-affricate'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_laf' + audio_ext},
    ('labial'   ,'linguo-labial','lateral-affricate'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_laf' + audio_ext},
    ('labial'   ,'bilabial'     ,'lateral-fricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__lfr' + audio_ext},
    ('labial'   ,'labio-dental' ,'lateral-fricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_lfr' + audio_ext},
    ('labial'   ,'linguo-labial','lateral-fricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_lfr' + audio_ext},
    ('labial'   ,'bilabial'     ,'lateral-approximant'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__lap' + audio_ext},
    ('labial'   ,'labio-dental' ,'lateral-approximant'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_lap' + audio_ext},
    ('labial'   ,'linguo-labial','lateral-approximant'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_lap' + audio_ext},
    ('labial'   ,'bilabial'     ,'lateral-flap'              ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_b__lfl' + audio_ext},
    ('labial'   ,'labio-dental' ,'lateral-flap'              ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ld_lfl' + audio_ext},
    ('labial'   ,'linguo-labial','lateral-flap'              ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'l_ll_lfl' + audio_ext},


    ('coronal'  ,'linguo-labial'  ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_n'  + audio_ext},
    ('coronal'  ,'dental'         ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__n'  + audio_ext},
    ('coronal'  ,'alveolar'       ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__n'  + audio_ext},
    ('coronal'  ,'palato-alveolar','nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_n' + audio_ext},
    ('coronal'  ,'retroflex'      ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__n' + audio_ext},
    ('coronal'  ,'alveolo-palatal','nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_n' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_s'   + audio_ext},
    ('coronal'  ,'dental'         ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__s'   + audio_ext},
    ('coronal'  ,'alveolar'       ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__s'   + audio_ext},
    ('coronal'  ,'palato-alveolar','stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_s'   + audio_ext},
    ('coronal'  ,'retroflex'      ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__s'   + audio_ext},
    ('coronal'  ,'alveolo-palatal','stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_s'   + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_sa'   + audio_ext},
    ('coronal'  ,'dental'         ,'sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__sa'   + audio_ext},
    ('coronal'  ,'alveolar'       ,'sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__sa'   + audio_ext},
    ('coronal'  ,'palato-alveolar','sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_sa' + audio_ext},
    ('coronal'  ,'retroflex'      ,'sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__sa' + audio_ext},
    ('coronal'  ,'alveolo-palatal','sibilant-affricate'      ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_sa' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_nsa' + audio_ext},
    ('coronal'  ,'dental'         ,'non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__nsa' + audio_ext},
    ('coronal'  ,'alveolar'       ,'non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__nsa' + audio_ext},
    ('coronal'  ,'palato-alveolar','non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_nsa' + audio_ext},
    ('coronal'  ,'retroflex'      ,'non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__nsa' + audio_ext},
    ('coronal'  ,'alveolo-palatal','non-sibilant-affricate'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_nsa' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_nsf' + audio_ext},
    ('coronal'  ,'dental'         ,'non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__nsf' + audio_ext},
    ('coronal'  ,'alveolar'       ,'non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__nsf' + audio_ext},
    ('coronal'  ,'palato-alveolar','non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_nsf'  + audio_ext},
    ('coronal'  ,'retroflex'      ,'non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__nsf'  + audio_ext},
    ('coronal'  ,'alveolo-palatal','non-sibilant-fricative'  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_nsf'  + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_a' + audio_ext},
    ('coronal'  ,'dental'         ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__a' + audio_ext},
    ('coronal'  ,'alveolar'       ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__a' + audio_ext},
    ('coronal'  ,'palato-alveolar','approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_a'   + audio_ext},
    ('coronal'  ,'retroflex'      ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__a'   + audio_ext},
    ('coronal'  ,'alveolo-palatal','approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_a'   + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_f'   + audio_ext},
    ('coronal'  ,'dental'         ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__f'   + audio_ext},
    ('coronal'  ,'alveolar'       ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__f'   + audio_ext},
    ('coronal'  ,'palato-alveolar','flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_f'   + audio_ext},
    ('coronal'  ,'retroflex'      ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__f'   + audio_ext},
    ('coronal'  ,'alveolo-palatal','flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_f'   + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_t' + audio_ext},
    ('coronal'  ,'dental'         ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__t' + audio_ext},
    ('coronal'  ,'alveolar'       ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__t' + audio_ext},
    ('coronal'  ,'palato-alveolar','trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_t' + audio_ext},
    ('coronal'  ,'retroflex'      ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__t' + audio_ext},
    ('coronal'  ,'alveolo-palatal','trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_t' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_la' + audio_ext},
    ('coronal'  ,'dental'         ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__la' + audio_ext},
    ('coronal'  ,'alveolar'       ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__la' + audio_ext},
    ('coronal'  ,'palato-alveolar','lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_la' + audio_ext},
    ('coronal'  ,'retroflex'      ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__la' + audio_ext},
    ('coronal'  ,'alveolo-palatal','lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_la' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_lf'  + audio_ext},
    ('coronal'  ,'dental'         ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__lf'  + audio_ext},
    ('coronal'  ,'alveolar'       ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__lf'  + audio_ext},
    ('coronal'  ,'palato-alveolar','lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_lf' + audio_ext},
    ('coronal'  ,'retroflex'      ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__lf' + audio_ext},
    ('coronal'  ,'alveolo-palatal','lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_lf' + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_lap'   + audio_ext},
    ('coronal'  ,'dental'         ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__lap'   + audio_ext},
    ('coronal'  ,'alveolar'       ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__lap'   + audio_ext},
    ('coronal'  ,'palato-alveolar','lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_lap'   + audio_ext},
    ('coronal'  ,'retroflex'      ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__lap'   + audio_ext},
    ('coronal'  ,'alveolo-palatal','lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_lap'   + audio_ext},
    ('coronal'  ,'linguo-labial'  ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ll_laf'   + audio_ext},
    ('coronal'  ,'dental'         ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_d__laf'   + audio_ext},
    ('coronal'  ,'alveolar'       ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_a__laf'   + audio_ext},
    ('coronal'  ,'palato-alveolar','lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_pa_laf' + audio_ext},
    ('coronal'  ,'retroflex'      ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_r__laf' + audio_ext},
    ('coronal'  ,'alveolo-palatal','lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'c_ap_laf' + audio_ext},


    ('dorsal'   ,'alveolo-palatal','nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_n' + audio_ext},
    ('dorsal'   ,'palatal'        ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__n' + audio_ext},
    ('dorsal'   ,'velar'          ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__n' + audio_ext},
    ('dorsal'   ,'uvular'         ,'nasal'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__n' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_s' + audio_ext},
    ('dorsal'   ,'palatal'        ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__s' + audio_ext},
    ('dorsal'   ,'velar'          ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__s' + audio_ext},
    ('dorsal'   ,'uvular'         ,'stop'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__s' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','sibilant-affricative'    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_sa' + audio_ext},
    ('dorsal'   ,'palatal'        ,'sibilant-affricative'    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__sa' + audio_ext},
    ('dorsal'   ,'velar'          ,'sibilant-affricative'    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__sa' + audio_ext},
    ('dorsal'   ,'uvular'         ,'sibilant-affricative'    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__sa' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','non-sibilant-affricative'):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_nsa' + audio_ext},
    ('dorsal'   ,'palatal'        ,'non-sibilant-affricative'):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__nsa' + audio_ext},
    ('dorsal'   ,'velar'          ,'non-sibilant-affricative'):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__nsa' + audio_ext},
    ('dorsal'   ,'uvular'         ,'non-sibilant-affricative'):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__nsa' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_a' + audio_ext},
    ('dorsal'   ,'palatal'        ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__a' + audio_ext},
    ('dorsal'   ,'velar'          ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__a' + audio_ext},
    ('dorsal'   ,'uvular'         ,'approximant'             ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__a' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_f' + audio_ext},
    ('dorsal'   ,'palatal'        ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__f' + audio_ext},
    ('dorsal'   ,'velar'          ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__f' + audio_ext},
    ('dorsal'   ,'uvular'         ,'flap'                    ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__f' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_t' + audio_ext},
    ('dorsal'   ,'palatal'        ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__t' + audio_ext},
    ('dorsal'   ,'velar'          ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__t' + audio_ext},
    ('dorsal'   ,'uvular'         ,'trill'                   ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__t' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_la' + audio_ext},
    ('dorsal'   ,'palatal'        ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__la' + audio_ext},
    ('dorsal'   ,'velar'          ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__la' + audio_ext},
    ('dorsal'   ,'uvular'         ,'lateral-affricate'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__la' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_lf' + audio_ext},
    ('dorsal'   ,'palatal'        ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__lf' + audio_ext},
    ('dorsal'   ,'velar'          ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__lf' + audio_ext},
    ('dorsal'   ,'uvular'         ,'lateral-fricative'       ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__lf' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_lap' + audio_ext},
    ('dorsal'   ,'palatal'        ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__lap' + audio_ext},
    ('dorsal'   ,'velar'          ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__lap' + audio_ext},
    ('dorsal'   ,'uvular'         ,'lateral-approximant'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__lap' + audio_ext},
    ('dorsal'   ,'alveolo-palatal','lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_ap_laf' + audio_ext},
    ('dorsal'   ,'palatal'        ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_p__laf' + audio_ext},
    ('dorsal'   ,'velar'          ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_v__laf' + audio_ext},
    ('dorsal'   ,'uvular'         ,'lateral-flap'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'd_u__laf' + audio_ext},


    ('laryngeal','uvular'    ,'nasal'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__n' + audio_ext},
    ('laryngeal','epiglottal','nasal'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__n' + audio_ext},
    ('laryngeal','glottal'   ,'nasal'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__n' + audio_ext},
    ('laryngeal','uvular'    ,'stop'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__s' + audio_ext},
    ('laryngeal','epiglottal','stop'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__s' + audio_ext},
    ('laryngeal','glottal'   ,'stop'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__s' + audio_ext},
    ('laryngeal','uvular'    ,'sibilant-affricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__sa' + audio_ext},
    ('laryngeal','epiglottal','sibilant-affricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__sa' + audio_ext},
    ('laryngeal','glottal'   ,'sibilant-affricative'         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__sa' + audio_ext},
    ('laryngeal','uvular'    ,'non-sibilant-affricative'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__nsa' + audio_ext},
    ('laryngeal','epiglottal','non-sibilant-affricative'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__nsa' + audio_ext},
    ('laryngeal','glottal'   ,'non-sibilant-affricative'     ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__nsa' + audio_ext},
    ('laryngeal','uvular'    ,'approximant'                  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__a' + audio_ext},
    ('laryngeal','epiglottal','approximant'                  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__a' + audio_ext},
    ('laryngeal','glottal'   ,'approximant'                  ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__a' + audio_ext},
    ('laryngeal','uvular'    ,'flap'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__f' + audio_ext},
    ('laryngeal','epiglottal','flap'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__f' + audio_ext},
    ('laryngeal','glottal'   ,'flap'                         ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__f' + audio_ext},
    ('laryngeal','uvular'    ,'trill'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__t' + audio_ext},
    ('laryngeal','epiglottal','trill'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__t' + audio_ext},
    ('laryngeal','glottal'   ,'trill'                        ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__t' + audio_ext},
    ('laryngeal','uvular'    ,'lateral-affricate'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__la' + audio_ext},
    ('laryngeal','epiglottal','lateral-affricate'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__la' + audio_ext},
    ('laryngeal','glottal'   ,'lateral-affricate'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__la' + audio_ext},
    ('laryngeal','uvular'    ,'lateral-fricative'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__lf' + audio_ext},
    ('laryngeal','epiglottal','lateral-fricative'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__lf' + audio_ext},
    ('laryngeal','glottal'   ,'lateral-fricative'            ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__lf' + audio_ext},
    ('laryngeal','uvular'    ,'lateral-approximant'          ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__lap' + audio_ext},
    ('laryngeal','epiglottal','lateral-approximant'          ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__lap' + audio_ext},
    ('laryngeal','glottal'   ,'lateral-approximant'          ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__lap' + audio_ext},
    ('laryngeal','uvular'    ,'lateral-flap'                 ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_u__laf' + audio_ext},
    ('laryngeal','epiglottal','lateral-flap'                 ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_e__laf' + audio_ext},
    ('laryngeal','glottal'   ,'lateral-flap'                 ):{'ipa_val':u'\u0000'      , 'path':audio_path + 'lg_g__laf' + audio_ext}
}


vowels = {
    ('front'     ,'close'     ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_c' + audio_ext},
    ('front'     ,'near-close'):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_nc' + audio_ext},
    ('front'     ,'close-mid' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_cm' + audio_ext},
    ('front'     ,'mid'       ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_m' + audio_ext},
    ('front'     ,'open-mid'  ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_om' + audio_ext},
    ('front'     ,'near-open' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_no' + audio_ext},
    ('front'     ,'open'      ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'v_f_o' + audio_ext},
                                             
    ('near-front','close'     ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-front','near-close'):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ll_lfl' + audio_ext},
    ('near-front','close-mid' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-front','mid'       ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-front','open-mid'  ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-front','near-open' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-front','open'      ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
                                             
    ('central'   ,'close'     ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'near-close'):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'close-mid' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'mid'       ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'open-mid'  ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'near-open' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('central'   ,'open'      ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
                                             
    ('near-back' ,'close'     ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'near-close'):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'close-mid' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'mid'       ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'open-mid'  ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'near-open' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('near-back' ,'open'      ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
                                             
    ('back'      ,'close'     ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'near-close'):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'close-mid' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'mid'       ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'open-mid'  ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'near-open' ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
    ('back'      ,'open'      ):{'ipa_val' : u'\u0000', 'path' : audio_path + 'l_ld_lfl' + audio_ext},
}


print('Using IPA_primitives.')
#ipa_temp = ipa_val(u'\u0000', 'this is a string')
#print(ipa_temp)
#print(ipa_temp[1])
print(pulmonic_consonants['labial','bilabial','nasal']['ipa_val'].encode('UTF-16'))
#for key in pulmonic_consonants.keys():
#    print("{key} => {char}".format(key=key, char=pulmonic_consonants[key]['ipa_val'].encode('utf16')))
    #print(key + ' => ' + pulmonic_consonants[key])[1])
